spring:
  application:
    name: manage-product
  cloud:
    config:
      uri: "http://localhost:8888/"

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8889
