product:
  items:
    - productId: 1
      costPrice: 100
      createdBy: abhinawb
      createdDate: 2025-07-06
      description: Pen
      lastModifiedBy: abhinawb
      lastModifiedDate: 2025-07-06
      productCategory: Stationary
      productName: Pilot Pen
      quantityAvailable: 500
      sellPrice: 150
      status: Y
      uomId: 1
      version: 0
    - productId: 2
      costPrice: 100
      createdBy: abhinawb
      createdDate: 2025-07-06
      description: Pencil
      lastModifiedBy: abhinawb
      lastModifiedDate: 2025-07-06
      productCategory: Stationary
      productName: Black Pencil
      quantityAvailable: 200
      sellPrice: 150
      status: Y
      uomId: 1
      version: 0
